### ISSUE TITLE
Which License Should we use for this project

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#1]
We believe MIT license is appropriate, but let's discuss it.

**Comment by carolyncole** [comment]
child of #2

**Comment by hackmastera** [comment]
According to DRDS folks, we generally use apache2

**Comment by carolyncole** [comment]
@jpstroop do you have any feelings on the license?  We are planning to follow DRDS and use apache2 unless there are reasons not to.

**Comment by jpstroop** [comment]
The U has never given me useful/clear advice on this, despite several attempts with a variety of offices. I've always liked the [BSD 3-Clause](https://choosealicense.com/licenses/bsd-3-clause/) for stuff I've done on my own, but for work we do for Princeton, I agree that Apache 2 is best.
