### ISSUE TITLE
Update ./spec/views/travel_requests

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1010]
Run
```
bundle exec rspec ./spec/views/travel_requests
```

Update the lux component with the correct name
Make the test pass.

Checkout a new branch from [PR#984](https://github.com/pulibrary/approvals/pull/984)

Open the PR against [PR#984](https://github.com/pulibrary/approvals/pull/984)

**Comment by sandbergja** [comment]
Closed by #1029
