### ISSUE TITLE
Update specs: ./spec/features/new_absence_request_spec.rb

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1016]
Run
```
bundle exec rspec ./spec/features/new_absence_request_spec.rb
```
Update the lux component name.
Make the test pass.

Checkout a new branch from [PR#984](https://github.com/pulibrary/approvals/pull/984)

Open the PR against [PR#984](https://github.com/pulibrary/approvals/pull/984)

**Comment by kevinreiss** [comment]
Date Range component issue.

**Comment by sandbergja** [comment]
There still seems to be a date range issue (there is an error message that says that there is no end date), but we will track this in a separate ticket.
