### ISSUE TITLE
Update specs: ./spec/features/my_approval_requests_spec.rb

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1018]
Run
```
bundle exec rspec ./spec/features/my_approval_requests_spec.rb
```
Update the lux component name.
Make the test pass.

Checkout a new branch from [PR#984](https://github.com/pulibrary/approvals/pull/984)

Open the PR against [PR#984](https://github.com/pulibrary/approvals/pull/984)

**Comment by kevinreiss** [comment]
Filters cannot be applied on on the report screen.

**Comment by christinach** [comment]
The tests are now passing.
