### ISSUE TITLE
Update specs: ./spec/controllers/requests_controller_spec.rb

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1021]
Run
```
bundle exec rspec ./spec/controllers/requests_controller_spec.rb
```
Update the lux component name.
Make the test pass.

Checkout a new branch from [PR#984](https://github.com/pulibrary/approvals/pull/984)

Open the PR against [PR#984](https://github.com/pulibrary/approvals/pull/984)

**Comment by maxkadel** [comment]
All except for `RequestsController GET #my_approval_requests runs reasonably fast` are passing - this has always been a flaky test for me locally, but passes in CI. This is an overall performance issue, not a lux-styleguidist issue.
