### ISSUE TITLE
[lux-styleguidist] LOGIN has incorrect padding between the text and the LogIN button

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1048]
In dev tools compare the lux-styleguidist LogIn screen vs the one in production.
Notice that the padding is different. 
Specifically: 
    [in production](https://approvals.princeton.edu/): `.lux-text-style {  ..,.., margin: 0 0 16px}`  
    using the lux-styleguidist branch: `.lux-text-style {  ..,.., margin: 0}`

Find why this is happening and fix it. 
Do not add a custom padding.

**Comment by kevinreiss** [comment]
Make sure to look at function's in lux-styleguidest that calculate padding/spacing on components.

**Comment by sandbergja** [comment]
closed by #1064
