### ISSUE TITLE
[lux-styleguidist][New travel request] when keying in .lux-input-field input it displays [object InputEvent]]

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1050]
In `New travel request -> Anticipated Expenses`.
Type a value in `Occurrences` or `Cost per Occurrence`. 
 lux-input-field input will display [object InputEvent]. 

![Screenshot 2024-03-01 at 8 28 14 AM](https://github.com/pulibrary/approvals/assets/9905193/d2976596-9ce6-4f3e-a0b3-f8a973cc5f32)

Related spec: `bundle exec rspec ./spec/features/new_travel_request_spec.rb:60`

**Comment by sandbergja** [comment]
closed by #1061
