### ISSUE TITLE
[lux-styleguidist][New Travel request][Event name] Adding a number in the event name field I expect to see a warning in the screen

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1054]
New travel request 
In the event name type: 'Geometry 360' 
Hit the Tabkey or click outside of the input field
There is no warning "It looks like you have a date in this field. Please remove." on the screen.

Related spec: `bundle exec rspec ./spec/features/new_travel_request_spec.rb:110`

Notes: Add a breakpoint and see how many events are fired (emitted) by the autocomplete. If there are two events or a multiple of two check that the events are declared in the LuxAutocompleteInput component.

**Comment by sandbergja** [comment]
Fixed by https://github.com/pulibrary/approvals/pull/1058
