### ISSUE TITLE
[lux-styleguidist] absence request form should be centered on the screen

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#1067]
### Current display for lux-styleguidist branch
There is no padding on the left or right of the absence request form: https://approvals-staging.princeton.edu/absence_requests/new

![the form goes all the way to the very edge of the screen](https://github.com/pulibrary/approvals/assets/7086943/84c5fe04-856a-4ea7-96cf-2213ed72d34c)

### Desired display for lux-styleguidist branch (current display in main)
The form is centered on the screen, with padding on each side:
![the form is centered on the screen](https://github.com/pulibrary/approvals/assets/7086943/483805f9-03f0-49cf-bf91-a25ce52355f3)

### Acceptance criteria

- [x] The form has the same spacing as on main

**Comment by christinach** [comment]
On the main branch I'm seeing exactly what I see in the lux-styleguidist branch. 
@sandbergja if you zoom out you take the screen you have in the second image. Could this be the case when you tested it?

Main branch 100% zoom:

<img width="1420" alt="Screenshot 2024-03-06 at 2 26 02 PM" src="https://github.com/pulibrary/approvals/assets/9905193/a1417268-b085-4d32-b6a5-4b446d47cbba">

Main branch 75%:
<img width="1414" alt="Screenshot 2024-03-06 at 2 27 20 PM" src="https://github.com/pulibrary/approvals/assets/9905193/94813804-b294-420b-87e5-b7f0d5f6f5c7">

**Comment by christinach** [comment]
We can reopen it if someone else sees the form centered in 100% zoom (in the main branch)
