### ISSUE TITLE
[lux-styleguidist] When viewing an absence, the cancel button is really big

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#1068]
### Current display on lux-styleguidist

When viewing an absence, the cancel button is a different size than the other two

![Cancel button is way bigger than the two buttons on either side, and it looks goofy](https://github.com/pulibrary/approvals/assets/7086943/59ae2579-cc33-4a16-8c5a-d7160b5876b8)

### Desired display on lux-styleguidist / current display on main

All buttons are the same size:

![all buttons are the same size](https://github.com/pulibrary/approvals/assets/7086943/15f07703-8bd4-4f8f-8474-b423d7bc444a)

### Acceptance criteria

- [ ] All buttons in this part of the screen are the same size

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/lux-styleguidist/pull/133/files
