### ISSUE TITLE
Reports Screen in Staging produces 500 Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#1070]
### Expected behavior
When you act as kr2 in approvals staging the report screen loads. 

### Actual behavior
When you act as kr2 in approvals staging the report screen gives a 500 error. 

### Steps to replicate
Login as kr2 or act on this net ID's behalf. 

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Honeybadger link and code snippet, if applicable
See https://app.honeybadger.io/projects/67941/faults/105141738. 

```
```

**Comment by christinach** [comment]
@kevinreiss I run the rake task to add you as a delegator and I can act on your behalf. Can you try again to view your requests.

**Comment by kevinreiss** [comment]
I can see these now.
