### ISSUE TITLE
[my delegations]Update message in tip-card

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#1079]
[My delegations page](https://approvals.princeton.edu/delegates/to_assume)
Update message in tip card to be:

`Please use this feature with care as it allows you to act on someone's behalf.`

[My delegates](https://approvals.princeton.edu/delegates/)

Update message to be:
`Please use this feature with care as it allows other people whom you designate to act on your behalf.`

**Comment by kevinreiss** [comment]
Why don't we just keep it simpler and say this

```Please use this feature with care as it allows you to act on someone's behalf. Delegation must never be used for approving any type of request.```
