### ISSUE TITLE
[lux-styleguidist] The event date popup isn't getting the correct body

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/approvals#1082]
### Expected behavior
A message should appear in the modal with the text that appears to be a date in the event title

### Actual behavior
Instead we only see 'default body'

### Steps to replicate
Create a new request with at least two consecutive numbers in the title "example 360"

### Impact of this bug
The message doesn't help the user understand what is wrong with the request

### Implementation notes, if any
My guess from what I see is the correct message isn't being passed into the slot correctly.

**Comment by sandbergja** [comment]
closed by #1092
