### ISSUE TITLE
[lux-styleguidist] Resolve Selenium::WebDriver::Error::ElementClickInterceptedError in Spec

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#1095]
Currently seen in ./spec/features/decide_travel_request_spec.rb on https://github.com/pulibrary/lux-styleguidist/pull/134, spec/features/decide_travel_request_spec.rb, 

## Notes
Could possibly be catching a real bug that is occurring only at certain screen sizes, this is set in capybara configuration.

**Comment by sandbergja** [comment]
I didn't get too far on this one, but some notes about spec/features/decide_travel_request_spec.rb:84:

- These tests pass if you use the `RUN_IN_BROWSER` environment variable.
- I looked at this screen in several screen sizes.  While the autocomplete dropdown certainly covers certain buttons, I did not find any screen sizes at which the dropdown covered the "Change Event Name" button.
- The autocomplete looks pretty much the same to me on the approvals main branch as the lux-styleguidist branch.
