### ISSUE TITLE
Business logic for status

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#112]
When a request is saved, or a state change is saved, status should be computed based on the approval events.

**Comment by carolyncole** [comment]
When a StateChange is saved then the Request attached to the StateChange needs to have it's status updated. The plane is to add an active record callback before_save to recalculate the status.

Use Diagrams to determine business logic: 
[Absence](https://docs.google.com/drawings/d/1o44sluFPYPSfODoCRTSbkdGjimkm63y0JDQmIHPXvvI/edit)
[Travel](https://docs.google.com/drawings/d/1Anv2H4h66hzFP6OO2mAeniQxafwtK2S8tTsJ7_niC0k/edit)
