### ISSUE TITLE
Move to new mail Relay server Approvals

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#1153]
Review https://github.com/pulibrary/approvals/pull/1147 for each of our application that utilizes the mail relay.  Confirm that the following is true after deploying to prod:

- I can still send and receive emails
- /var/log/mail on lib-ponyexpr-prod shows that the mails are sent successfully
- For a rails app, make sure that `enable_starttls` is false.  See https://github.com/pulibrary/orangelight/pull/4026 and https://github.com/pulibrary/pdc_describe/pull/1843 for examples.

**Comment by maxkadel** [comment]
Successfully sent mail after [adding approvals production servers to the allow list](https://github.com/pulibrary/princeton_ansible/pull/5046/files)
