### ISSUE TITLE
User gets the "You are not authorized to view this material" message when CAS gives us a netid in all caps

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#1173]
### Expected behavior

User can log in, whether CAS decides to give us their netid in all caps or lowercase.

### Actual behavior

This blocks Nish from logging in on Chrome.  She gets the error message "You are not authorized to view this material" and Datadog shows that her netid is getting passed in all caps

### Steps to replicate

We can replicate this in a test case, and then check with Nish when we have a fix.

### Impact of this bug

High, Nish can't do her work in approvals on Chrome.

**Comment by kevinreiss** [comment]
It seems we can consider this closed based on the merged PR.
