### ISSUE TITLE
Align absence type values to self-service

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#119]
from @jpstroop: The values RBSC was tracking were a little too detailed/personal. I'd suggest aligning these directly to the values the University tracks if you haven't already.

**Comment by jpstroop** [comment]
![Screen Shot 2019-05-03 at 12 37 37 PM](https://user-images.githubusercontent.com/999701/57152009-4ddc7800-6da0-11e9-90f6-e0a3acc4ddbb.png)

**Comment by hackmastera** [comment]
@jpstroop that matches our list, except that ours also has:
- research_days
- work_from_home

I think both of these came from conversations with departmental users. Do they sound right to you?

**Comment by hackmastera** [comment]
We decided these are good.
