### ISSUE TITLE
Create workflow diagrams

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#125]

**Comment by carolyncole** [comment]
Here is the initial diagram for absence: https://docs.google.com/drawings/d/1o44sluFPYPSfODoCRTSbkdGjimkm63y0JDQmIHPXvvI/edit

**Comment by carolyncole** [comment]
https://docs.google.com/drawings/d/1Anv2H4h66hzFP6OO2mAeniQxafwtK2S8tTsJ7_niC0k/edit

Questions:
1. Do approvers of a request want confirmation when it has been fully approved by the department head?
1. We have put in Approvers getting notifications on changes, is this desired?
