### ISSUE TITLE
Requestor Overview/ Dashboard Wireframe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#14]
child of #12 
How are we going to show the requestor all the leave/ travel they have requested?  Is it a list or a calendar view?

**Comment by sdellis** [comment]
Supervisors may see two columns, one for their own requests, and another list of the requests they need to take action on (approve/deny).

**Comment by carolyncole** [comment]
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/0c5cf3c6-170e-4e07-8bc8-0360960056cc/Requestor-Dashboard
