### ISSUE TITLE
Requestor Status - Time Off Balance

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#15]
As a requester, I want to see my time-off balance so that I know if I can request additional time off.

I want to see:
 * current balance as reported by HR's system, with date processed by that system
 * Total hours requested; ensure weekends / holidays are not included

#175 includes the additional advanced features beyond MVP.

Notes:
* Integration with Self Service for the data
    * information warehouse #141
* Displayed location #14

**Comment by sdellis** [comment]
* How do we initially load balance data?
* How do we verify periodically that balances match in each system?

**Comment by carolyncole** [comment]
Validation of balances matching is beyond MVP.  The value will be reported by HR Self Service (CALM).   Any additional calculations would be on demand.
