### ISSUE TITLE
Set status of Requests to "Recorded"

### ISSUE THREAD

**Issue by sdellis** [pulibrary/approvals#155]
As an Administrative Assistant, I want to mark all the requests I've recorded so I don't enter them again. (bulk edit)

As an Administrative Assistant, I want to mark a single request as "recorded" so I can go back and mark any that I've missed.

Related to #13

**Comment by sdellis** [comment]
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/6c178f1d-c37d-4c12-98e9-35fadda90745/Absence-Reporting-Form?fullscreen

**Comment by kevinreiss** [comment]
Users have a record button. AA's will not be handling this per LLT.
