### ISSUE TITLE
Change the public name for application to `Leave and Travel Requests`

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#165]
"Approvals" was confusing to some users.

Additionally change the URL to library.princeton.edu/away

**Comment by carolyncole** [comment]
@jpstroop Do we want to stick with Approvals?   The confusion came from the conflict with collection building and acquisition approvals.  

Possible options:  
  * Approvals
  * PUL Requests
  * Travel and Absence Approvals

**Comment by jpstroop** [comment]
I think some kind of branding is worth thinking about. I'll think about it, but am open to ideas

Sent via mobile. Please excuse typos and brevity.

________________________________

**Comment by carolyncole** [comment]
The name should be: `Leave and Travel Requests`
url should be: `library.princeton.edu/away`
