### ISSUE TITLE
Other categories / comp time

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#166]
As a supervisor I need to approve non-official types of absences so that I can keep track of when my direct reports will be in/out of the office.

As an AA I need to know when people in my department will be out of the office for non-official types of absences.

**Comment by hackmastera** [comment]
not mvp

**Comment by carolyncole** [comment]
@jpstroop Do we want to allow for an other category in the system?  We have been specifically asked about comp time.

**Comment by hackmastera** [comment]
Answer: We could do this, but it's confirmed as not MVP.

**Comment by kevinreiss** [comment]
LLT provided a list of definitive types of leave to track, comp time not included.
