### ISSUE TITLE
Create a config file for storing university holidays

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#168]
To ignore holidays in calculation of hours, we need to know what they are.

Config file should contain comments regarding how to update.

Persons responsible for yearly update should be determined, and calendar reminders should be set for April/May to update the config file.

**Comment by carolyncole** [comment]
Ask  with data warehouse folks.

**Comment by kevinreiss** [comment]
Tara was going to look into this but it seemed like this data point was out of scope for the information warehouse. Sounded like it was in peoplesoft but this would likely be one we'd need to set up a config file where these would be coded based on the published University calendar.
