### ISSUE TITLE
Reporting permissions

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#177]
@jpstroop for discussion at our next meeting. Do we want to ensure only certain people can see certain data? If so, what should those limitations be? How do they interact with the AA role (e.g. issue #154) and the browse events use case (#152, not mvp)?

**Comment by jpstroop** [comment]
>Do we want to ensure only certain people can see certain data?
What have you heard in your feedback? I'd like to hear real use cases for all data not being available to any auth'd user. The alternative, I guess, it to only be able to see all of the data below yourself in your admin hierarchy, but personally I would rather see effort go into more robust reporting in support of, e.g., #154 and #152

**Comment by carolyncole** [comment]
We should only allow direct reports or below visibility.

**Comment by kevinreiss** [comment]
Reports feature implements this.
