### ISSUE TITLE
Define / finalize MVP

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#178]
@jpstroop for discussion at our next meeting.

Should we work on both travel and absence aspects of the system for MVP or should we focus on one or the other first?

**Comment by jpstroop** [comment]
I feel as though those are problems we promised the system would solve (one system, one consistent workflow), so if both are possible, I think it would make the first iteration more compelling. Is there anything you need me to answer/anything I can do to help facilitate this?
