### ISSUE TITLE
Implement Absence Approve/Deny Form

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#187]
Implement the Approve Deny form for a supervisor to approve or deny an absence request:
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/c87ae3d7-572c-4125-8cad-bca427fe7524/Supervisor-Leave-Approval-Pending-

**Comment by hackmastera** [comment]
Perhaps this should be implemented as a show page, with form elements dependent on the current user.
