### ISSUE TITLE
Content of supervisor new request notification

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#20]
child of #20

When a requestor makes a request what are the contents of the notification that should be sent to the supervisor. Follow similar format to #9

**Comment by kevinreiss** [comment]
Borrowing from the current system:

"""
The following leave request was submitted by [Employee Name] on 6/4/19.

To review the request for approval go to [link to request]

Type: [Type of leave request]
Dates Away: Start Date - End Date
Total absence time in hours: [14.5] (If applicable - only absence requests)
Destination: Princeton (If applicable  - only travel requests)
Event: [Conference I am going to] (If applicable - only travel requests
"""
