### ISSUE TITLE
Advanced Search Box on My Requests

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#206]
On the my request screen the search box will include just a keyword by default.

To add additional power to the search we want to be able to include the filters and sort within the search.
![Screen Shot 2019-06-12 at 9 19 48 AM](https://user-images.githubusercontent.com/1599081/59354519-49867180-8cf3-11e9-8dbf-a11eb39f89da.png)

This will not be part of the MVP, which is why we are breaking it out of #184

**Comment by carolyncole** [comment]
This was a use case for multiple filters, but we are currently only allowing for single select filters.  That means this is not required for mvp

**Comment by kevinreiss** [comment]
Not MVP
