### ISSUE TITLE
Check Lux icon maps to statuses

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#213]
@axamei   @sdellis another set mappings for you to verify.  I'm fairly certain they are incorrect...
 
```
      "pending" => "lux-icon-clock",
      "approved" => "lux-icon-approved",
      "denied" => "lux-icon-denied",
      "changes_requested" => "lux-icon-alert",
      "canceled" => "lux-icon-relaxed",
      "reported" => "lux-icon-file",
      "pending_cancelation" => "lux-icon-flower"
```

**Comment by axamei** [comment]
@carolyncole  after https://github.com/pulibrary/lux/pull/203 is merged, mappings for the status icons:

changes_requested => lux-icon-refresh
reported => lux-icon-reported
pending_cancelation => lux-icon-report-remove

**Comment by carolyncole** [comment]
We should verify that the changes for status have been implemented
