### ISSUE TITLE
What is a timely manner

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#22]
child of #21 

We need a definition for what a timely manner is in regards to supervisor approvals

Does this change based on a request for travel vs absence?

**Comment by sdellis** [comment]
We have received feedback from stakeholders that "timely manner" is:
* 2 days
* 1 week

**Comment by carolyncole** [comment]
@jpstroop What do you feel the timely manner should be?  2 days, one week, or some other value.

**Comment by jpstroop** [comment]
Might be good to put in a config file, but given that this covers both sick and vacation time, I think a daily nag is not unreasonable.

**Comment by jpstroop** [comment]
Perhaps weekly for business travel?

**Comment by hackmastera** [comment]
updated #21 with this info
