### ISSUE TITLE
Approvals Home Page Wireframe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#25]
child of #24 

Needs to include:
 *  Login button System
   * use LUX pattern for the login button
 * System description
 * Restriction blurb (restricted to library staff)
 * Use LUX patterns for header and footer

**Comment by carolyncole** [comment]
Version after use testing and shown to Jon https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/

**Comment by hackmastera** [comment]
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/

mobile: https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/e92f166e-bc64-4fa0-8561-76fef72f3242/MOBILE-Login
