### ISSUE TITLE
Error screen wireframe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#27]
child of #24 

Create a wireframe to display system errors including an unauthorized user.

Acceptance criteria:
500
403

**Comment by axamei** [comment]
We have these two very minimal screens (handles 403 and 500 errors):

https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/bdcd92eb-01b2-4e43-b546-c9800c2ccc25/Error-Pages-System-Error-500

https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/eb60eee3-d0d4-48aa-a9d5-89a61ca0b910/Error-Pages-Unauthorized-403
