### ISSUE TITLE
Any Request Show page Should show an indicator of request status

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#273]
On the Absence and the travel request show page we should show the status in the top left corner.  Include with the trip id for travel, make card in the corner for absence.  Make the status as the header, and change the card color to indicate status.  Red - denied, Green Approved, default color for pending.

also add the coloring to the my request page.

**Comment by axamei** [comment]
<img width="1175" alt="Screen Shot 2019-09-25 at 2 28 56 PM" src="https://user-images.githubusercontent.com/8161144/65629265-04840380-dfa1-11e9-93be-a7d1650b01e9.png">

Changing color of icons is not enough of a visual indicator. Try to use Tag component. See https://github.com/pulibrary/lux/issues/245
