### ISSUE TITLE
Include information about tax exempt status and procedure

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#283]
Princeton is exempt from paying sales tax in many cases (this varies by state and type of purchase).  We should include relevant information to encourage users to follow the process for getting an exemption, particularly for hotel and other large purchases.

See https://finance.princeton.edu/how-to/buying-paying/other-buy-pay/sales-tax-exemptions/index.xml

**Comment by carolyncole** [comment]
Have it in the show page and the email notification for when the travel is approved.

**Comment by carolyncole** [comment]
Will this just be on the travel policy page?

**Comment by carolyncole** [comment]
Assume this will be in the travel policy.
