### ISSUE TITLE
The staff report can have a vacant supervisor

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#298]
When processing the staff report there is a possibility that the supervisor would be vacant.  This somewhat ruins parsing the Staff hierarchy via the report.

**Comment by carolyncole** [comment]
Three options that I can think of:
1. Set the supervisor to the department head when the supervisor is Vacant
1. We could create some sort of configuration file to allow for the Vacant supervisor to be mapped to a person during the update process
1. Not change the supervisor of a person if it is vacant, and hand edit an initial report to put Esmé back in.

The Option 1 is the only entirely automated option. Option 3 only works if the supervisor has not left the university.  Option 2 allows us to put in "Acting" supervisors, which is the most flexible, but would require human intervention.

**Comment by sdellis** [comment]
A Department Head can assign a proxy/assistant for Absence Requests. Since Option 1 is the simplest approach, and the Department Head has to approve all Travel Requests anyway, it seems like the best option for MVP.

**Comment by kevinreiss** [comment]
I agree that option 1 seems the best course of action.
