### ISSUE TITLE
Wireframe for View Availability

### ISSUE THREAD

**Issue by sdellis** [pulibrary/approvals#32]

**Comment by hackmastera** [comment]
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/fcb0483f-bba0-48af-b4d8-a6fe36a0d96a/Reports

(no mobile wireframes for reporting)

**Comment by hackmastera** [comment]
not mvp

**Comment by sdellis** [comment]
Wireframe: https://xd.adobe.com/view/3f6e5993-29b6-4ea2-6818-e4b20010a0df-495f/screen/eeed0884-2966-4782-ba0e-0a6c29b55c4b/Availability
