### ISSUE TITLE
Implement form to support manual syncing from Approvals to HR System

### ISSUE THREAD

**Issue by sdellis** [pulibrary/approvals#36]
As a departmental administrator, I want to obtain a monthly report of the leave all staff in my department have taken so I can record it in HR self-service.

Possibilities:
* Be able to get an absence report and set that the item has been reported.

**Comment by sdellis** [comment]
Wireframe: 
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/6c178f1d-c37d-4c12-98e9-35fadda90745/Absence-Reporting-Form?fullscreen

**Comment by kevinreiss** [comment]
Per LLT policy.
