### ISSUE TITLE
Research Days Report

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#38]
As a departmental administrator with DOF staff members in my department I want to get a report of research days staff in my group have taken. 

related to #36

* Management Role 
   * assuming supervisor role is filled out in profile #17 maybe this could be part of the profile
* DOF Staff
   * assuming staff type is filled out in profile #17 maybe this could be part of the profile
* Report form #38 & #39

**Comment by kevinreiss** [comment]
Reports feature covers this.
