### ISSUE TITLE
Strange Pop Up when the date was chosen on Absence Form

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#382]
Something popped up when the date was chosen.  Not entirely sure what it was.  The user seemed surprised, but clicked it away.

Not entirely sure if there is really a problem...

**Comment by carolyncole** [comment]
Look at the recording for Jeremy to see what happened.

**Comment by axamei** [comment]
After looking at the video, the surprise came from the highlighting of dates in the datepicker. This was also unexpected by another user. Perhaps this was surprising due to their unfamiliarity with this particular datepicker's interface.
