### ISSUE TITLE
Report form Wireframe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#39]
child of #38 

We need to get reports of different information in the system based on date, roles, and event type.

This report form should only be available to supervisors, or for the user to see their current information.  This differs from the calendar view because we are looking for detailed information about the event, not just any event.

**Comment by sdellis** [comment]
Params:
* Dates
* Departments (ITIMS, Scholarly Content Services, etc.)
  * Divisions
  * Sections
  * Units
* People
* Events
* Leave/Absence Type

**Comment by hackmastera** [comment]
https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/fcb0483f-bba0-48af-b4d8-a6fe36a0d96a/Reports

(no mobile wireframes for reports; this is not a current use case)
