### ISSUE TITLE
Request Workflow

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#4]
Child of #3 
A Request will go through multiple states: Pending, Approved, Denied, Changes Requested

As the request moves through each state different communications will be triggered.  We need a way to define what states there are, what are the valid actions from each state, and what events should be triggered from each state.

Note: A travel request will traverse the entire chain of supervisors, through department head, for approval.

An absence request only requires approval from the supervisor.

**Comment by christinach** [comment]
How about a state: "Pending" ? (until manager's approval)

**Comment by carolyncole** [comment]
https://github.com/aasm/aasm may be a good tool to lean on for implementing the workflow

**Comment by sdellis** [comment]
I'm assuming Jon needs to get Anne's approval for his trips. Does Anne need to get some kind of approval for hers? Or for leave, I suppose? If not, she will be a special user who doesn't see the "My Requests" and only sees others' requests. Either that or "My Requests" will always be empty for her.
