### ISSUE TITLE
Implement Report Form

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#40]
Implement wireframes in #39
Child of #38 

Implement the wire frame and allow for reports to be created.  Will need to confine the people being reported on to either the user or a supervisors reports.

How will we allow for multiple layers of supervisor?
Can upper management report on other people's reports?

**Comment by sdellis** [comment]
Rows should be clickable, allowing one to drill down into the record.
Allow sorting on columns.

**Comment by carolyncole** [comment]
- [ ]  Filter by Date
- [ ]  Results Clickable
- [ ] Filter Results by person logged in. Should see your results and any results for your reports and their reports
