### ISSUE TITLE
Change the default homepage to My Requests if you are logged in

### ISSUE THREAD

**Issue by axamei** [pulibrary/approvals#419]
<img width="1680" alt="Screen Shot 2019-12-06 at 12 38 12 PM" src="https://user-images.githubusercontent.com/8161144/70343555-96bc4980-1825-11ea-92ae-080de547ff2b.png">

When a user is already logged in via CAS, if they go to the app, they will see a homepage with the name of the app, description and logout button. Instead we should modify welcome controller to redirect authenticated users to their "My Approvals" page.

We decided not to go change the buttons like the picture above.

**Comment by kevinreiss** [comment]
How to start new requests needs to be clear and obvious per user feedback.

**Comment by kevinreiss** [comment]
Modify welcome controller to redirect authenticated users to their "My Approvals" page.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/approvals/blob/master/spec/controllers/omniauth_callbacks_controller_spec.rb#L16-L23 . Here is the test for user that are not present in the system
