### ISSUE TITLE
Action Mailer Configuration

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#43]
https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
Can we get this from another system?

**Comment by hackmastera** [comment]
https://github.com/pulibrary/pul-the-hard-way/blob/master/services/smtp-mail-server.md

**Comment by hackmastera** [comment]
Configuration is PR'd; remaining is to add the production server to mail whitelist once we have a prod server. I removed this ticket as a blocker to other issues that we can reasonably work on without closing this. Blocking this on #183
