### ISSUE TITLE
Create a video on how to approve a travel request

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#448]
Login
Show the approval process
Host on youtube

**Comment by carolyncole** [comment]
@kevinreiss Can we just use a recording of the zoom training and link to it from the new help page? This avoids the need for a youtube channel, since zoom could hosts the video.

For the moment we could include screen shots on the page, which will be easier to change as the system evolves.

**Comment by kevinreiss** [comment]
https://drive.google.com/a/princeton.edu/file/d/1fCoa9NSSKPX9PukTF42aSR7MMROY0ylh/view?usp=sharing
