### ISSUE TITLE
Bi weekly staff balance information happens every two weeks.

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#477]
Biweekly staff balance is cycled in every two weeks. Change view to show “Balance as of …” to reflect it.

We need to find out when the two weeks starts.

**Comment by axamei** [comment]
https://finance.princeton.edu/payroll-labor-accounting/payroll/payroll-basics/monthly-and-biweekly-payroll-cycles

**Comment by carolyncole** [comment]
We will change the message to say "balance as of last pay period"
