### ISSUE TITLE
Reorganize the top level menu

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#491]
The new Request action should be at the top level.
The Logout, My Delegates, and Delegations should all be in a sub menu from the top bar.

**Comment by sdellis** [comment]
What should the title/label of the Logout, My Delegates, and Delegations sub menu be?

**Comment by sdellis** [comment]
Menu item grouping needs refinement. Still unclear as to how to proceed. Perhaps use a card sort approach to figure out what makes the most sense to users.
