### ISSUE TITLE
Create better alert message for missing required fields

### ISSUE THREAD

**Issue by axamei** [pulibrary/approvals#499]
Instead of the current error message, it should be something like "Required fields are missing values: Notes cannot be empty when denying a request." 

<img width="751" alt="Screen Shot 2020-01-28 at 10 04 13 AM" src="https://user-images.githubusercontent.com/8161144/73275773-a1f07d80-41b5-11ea-9359-3d7f46af9cca.png">

* <s>Change top line to say "1 error prohibited this request from being saved"</s> Refs #499
* Change error list to not say Notes Notes
* <s>Add margin to list item via css so it does not end up outside the header</s> Refs #499
* Notification for changes requested has "Travel request was successfully changes_requested"

**Comment by carolyncole** [comment]
ref #507
