### ISSUE TITLE
Request Data Model

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#5]
child of #3 

We need a data model for a Request.  This needs information like the Type of request, the time range for the request, and the current state of the request.

Should there be a separate request type for Leave vs Travel?  I am leaning towards no, since we what to show all request son a person, or department calendar.

- Common Fields
   - Creator (user)
   - Date Range
   - Note list (pointed at by notes)
   - Type (Travel, Absence)
   - Status (Pending, approved, denied: this is actually business logic based on the approval events, computed at save time)
   - Approval Event  [list]
- Travel only fields
   - Purpose
   - Level of participation (presenter, member, committee chair, committee member, other, site visit, training)
  - EventRequest
   - Travel Category (approver selects; not visible on create form) (business, professional development, discretionary)
- Absence
   -  Absence Type
       - consulting leave
       - vacation leave monthly
       - personal leave
       - sick leave
       - jury duty
       - death in family
       - research days (Dean of Faculty)
       - work from home (Dean of Faculty)

Request (all fields)
  - Absence
  - Travel

Could possibly utilize: https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html

**Comment by sdellis** [comment]
Anna suggests an inheritance model, perhaps?
