### ISSUE TITLE
Tab in browser does not have an icon it is blank

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#504]
![Screen Shot 2020-01-28 at 10 28 21 AM](https://user-images.githubusercontent.com/1599081/73277991-ecbfc480-41b8-11ea-883b-48807e4d90d0.png)

**Comment by axamei** [comment]
We can use these files https://drive.google.com/drive/folders/1xCcUmSxtGS1u6we9FW_QQM46x8FQw4wj
