### ISSUE TITLE
Turn off autofill in Travel Request Event form Input auto complete

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#511]
![Screen Shot 2020-01-28 at 2 36 53 PM](https://user-images.githubusercontent.com/1599081/73298634-a9c31880-41db-11ea-86f2-1ecd86f6d69b.png)

**Comment by sdellis** [comment]
This is a LastPass thing. We have turned autocomplete='off' in the markup, but  Lastpass user needs to have this option enabled: `Settings > Advanced > Allow pages to disable autofill`
