### ISSUE TITLE
Dates in email notification

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#540]
I think the wrong date might be used in the email notifications. I just received an email that listed "Dates Away 02/03/2020 - 02/03/2020" for a trip that was submitted on 02/03/2020, but is actually for a trip planned for 02/24 - 02/28.

**Comment by escowles** [comment]
Looking more closely at the web view, I think the issue is probably more specifically the Dates Away field, since I see "(02/03/2020 to 02/03/2020)" in the title also.

**Comment by sdellis** [comment]
@escowles it seems like this was user error? The Dates away field was just left at the default? Can we close it, or do you still consider this a bug?

**Comment by escowles** [comment]
@sdellis Yes, I think we can close this — when I create an event, I see the away dates get adjusted to match the event dates, and then the user can edit as needed. So I think an old version of the app is the most likely reason this happened.
