### ISSUE TITLE
Help users distinguish between dollars and # of instances

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/approvals#543]
This was a problem in the old system as well. I was putting in for one plane ticket that was $570, and I almost put in for 570 tickets at $1 each, e.g.:

![Screen Shot 2020-02-07 at 11 28 09 AM](https://user-images.githubusercontent.com/999701/74046865-51d79f00-499d-11ea-9d78-548ae6339768.png)

Some ideas:
 * Put a gray `$0.00` in the "Cost per Occurence" box
 * Put a `$` sign in front of the "Cost per Occurence" nox
 * Make "Occurrences" a dropdown. (This might just be a pain--I hate dropdowns in general, esp on mobile, and I'm not sure what the upper limit would be).

**Comment by carolyncole** [comment]
@jpstroop I added a hint to both the occurrences and the cost.  It is out in production now.  Does this satisfy the request?
![Screen Shot 2020-02-11 at 8 26 20 AM](https://user-images.githubusercontent.com/1599081/74240585-50152080-4ca8-11ea-849d-db201c5471e7.png)

**Comment by jpstroop** [comment]
👍🏻👍🏻👍🏻
