### ISSUE TITLE
Do we need to display the show button in the review screen?

### ISSUE THREAD

**Issue by axamei** [pulibrary/approvals#553]
It doesn't make too much sense to me to include the show button when a reviewer is attempting to review a request and needs to approve, deny, or request changes. Should we remove the show button? 
<img width="676" alt="Screen Shot 2020-02-10 at 12 17 21 PM" src="https://user-images.githubusercontent.com/8161144/74173129-8c407680-4bff-11ea-8e23-d1bf98936e8e.png">

**Comment by sdellis** [comment]
I agree, @axamei . This doesn't make sense and it may just be an artifact from prototyping.

**Comment by kevinreiss** [comment]
Yes, we can remove.
