### ISSUE TITLE
Notes Field Arbitrarily 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#559]
The DB datatype in Postgres is text, which should accept any number of characters, but the form textarea has a maxlength of 256 set as an attribute value.  Received user feedback that described the following issue:

```Issue with the approver filling in the notes field: I was in the middle of adding a few lines of a note as approver, when the edit function seemed to freeze (trying to back up and insert a parenthesis). Is this the result of a hidden character limit? Or some other glitch? If there is a character limit, the interface should say so..```

I'm not really sure what that really indicates but we should probably accept more than 256 characters for this field.

**Comment by sdellis** [comment]
LUX defaults to a 256 character limit if unspecified as an attribute. We should be able to set the max-length to whatever we think it should be.
