### ISSUE TITLE
Add Parking as an Expense Option

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#567]
1. Add parking as a discrete choice.

skip #2 since other is already in use
2. Rethink some of the transportation options (What is Ground Transportation vs. Other Transit)

**Comment by kevinreiss** [comment]
@jpstroop What do you think about adding Parking and removing "Other Transit". Some user feedback in the training sessions about what would ever actually go in this field.

**Comment by jpstroop** [comment]
I don't have an opinion, though I did need a place to put my scooter rental at UCLA last fall 🛴

**Comment by carolyncole** [comment]
I'll take an action to check if other transit has already been used.  If it has not been used let's remove it.
