### ISSUE TITLE
Change to allow commenting at any time

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#584]
I approved a travel request and it was sent upstream — and then I received a request on Slack to add a comment.

How it works now:
* Once I had approved the request, I could not see it to add a comment
* When the request was sent back for changes, it went back to the original requester. I received an email and could see the request again, but was not allowed to add a comment.
* When the original requester re-submitted the request, it went directly to the upstream approver.

What I would have liked:
* When I go to "Requests Awaiting My Approval", I would like to see items I have already approved, and be able to add comments.

**Comment by sdellis** [comment]
@escowles 

The expectation for the creator is to put in as much info as possible to help supervisors make a decision. The expectation for the supervisor is to express their support of the request. We should improve this helper text for supervisors. We also propose that anyone in the hierarchy should be able to comment on any request regardless of its state.

Would this support your use case?

Or are you also asking to be able to re-approve the request after the requestor makes changes? In other words, does it have to go all the way back through the approval hierarchy?

**Comment by kevinreiss** [comment]
See #628 for implementation.
