### ISSUE TITLE
Travel/Leave Request Form Wireframe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#6]
Child of #3 
related to #5

Design the look and feel for the travel/leave request form.

**Comment by sdellis** [comment]
One idea for a wireframe is to show the additional fields required by travel, but highlight as optional on the leave form?

Perhaps make the two forms distinct enough that people can immediately tell the difference.

**Comment by hackmastera** [comment]
Leave request: https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/c0a2dc69-2630-4200-980c-1f1bc0bff9f2/Requestor-New-Leave-Request

Travel request: https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/c87ae3d7-572c-4125-8cad-bca427fe7524/Supervisor-Leave-Approval-Pending-
