### ISSUE TITLE
Remove Trip ID

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#600]
Remove the Trip ID from it's prominent place in the request screen and in email notifications. Not sure what me might put it in it's place. We should discuss. This will be timed with an announcement on Travel Policy from LLT so keep in the backlog for now.

**Comment by sdellis** [comment]
#561 we were just asked to add the Trip ID into the email notifications. The Travel Policy will dictate how we handle this, so we can decide when we see the policy draft. We want to make sure that all are aware that abandoning the practice of tying the request to the concur report via TripID means that there will be no way to connect the records.

Once we see the policy, we will need a sprint to apply the changes the policy requires to the application. Will we be able to see a draft of the policy before it is made public to the rest of the Library?

**Comment by kevinreiss** [comment]
Yes, I did advise that we'd need some time after the policy is drafted to have a release of the app that will reflect it.

**Comment by sandbergja** [comment]
@kevinreiss is this ticket still valid?

**Comment by kevinreiss** [comment]
Closing. This inquiry has never come back up and the Trip ID is an important data point.
