### ISSUE TITLE
Reinforce that CALM is the System of Record in Approval Email Notifications.

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#601]
Leave approval emails should include text (and possibly a link to) that reminds users to enter their approved leave time in the CALM system. 

The biweelky folks may have a different link.

**Comment by sdellis** [comment]
Does this request mean that we can get rid of the "Recording Report" that was intended to support bulk recording by Admin Assistants? 

Can we get rid of the entire "recorded" concept entirely?

Does Communications have recommended wording and a link for this?
