### ISSUE TITLE
Add notice / alert info on delegation configuration screen

### ISSUE THREAD

**Issue by axamei** [pulibrary/approvals#611]
On the Delegation configuration screen (and possibly some kind of tooltip reminder when acting as a delegate):

> Please use this feature with care as it allows other people whom you designate to act on your behalf. Delegation must never be used for approving any type of request, with the exception of sick time, which departmental assistants may record on behalf of employees who call in sick without notice.

**Comment by sdellis** [comment]
If Delegation is only to be used for approving sick time, should we change the app to enforce this preferred behavior?

**Comment by kevinreiss** [comment]
No, I was told not to make that change at this time. If the need to further restrict this arises we will likely be asked to change the app to allow only admin assistants to become delegates.
