### ISSUE TITLE
Cost Estimate

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#62]
- Request
- Type
   - Get the type information from the previous system
- Amount
- Recurrence

**Comment by kevinreiss** [comment]
Type:


* Ground Transportation
* Lodging
* Meals and Related Tips
* Misc
* Registration Fees
* Rental Vehicle
* Transportation Air
* Transportation Auto Rental/Taxi
* Transportation Personal Auto (55&#162; per mile)
* Transportation Tolls/Other
* Transportation Train
