### ISSUE TITLE
Remove Record from System instead of ~~Create a Requests to Record Page ~~

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#659]
Mark as recorded is entirely confusing.  People believe we are interacting with the HR Self Service System.  We should just remove this feature.
~~that only shows you approved requests that are not recorded~~
~~Has link to HR self service~~
~~Has ability to mark items as recorded.~~

**Comment by kevinreiss** [comment]
Possibly add as a top-level option as "Requests to Record" like the supervisor
