### ISSUE TITLE
Are we requiring individuals to Mark the approved requests as recorded?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#662]
@jpstroop This seems like it could feel like extra work, but would be far easier to do as you go along, verses trying to come back and reconcile it later with the HR system.

At the moment the record function is optional, and we are uncertain what instructions to put. We are thinking this as a tracking mechanism for what to record in HR.

It could also just be removed as it might confuse the users into thinking they had recorded it in HR Self Service

**Comment by carolyncole** [comment]
![Screen Shot 2020-03-05 at 10 32 52 AM](https://user-images.githubusercontent.com/1599081/76003164-a9eabe00-5ed5-11ea-9341-f6d5f1658663.png)

**Comment by carolyncole** [comment]
We are going to close this since we are removing the mark as recorded.  The expectation was that the system would record the information in HR Self Service.

**Comment by jpstroop** [comment]
I'm sorry, I thought I commented. I think this might be a useful utility, even if it's not enforced or actionable in any way. I could imagine going to the app to check what needs recording, and using this as a flag to help me know what I've done and what I need to do. That said, maybe it would just be confusing.
