### ISSUE TITLE
Absence Request form Implementation

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/approvals#7]
child of #3 
Blocked by #6 

Implement the design of the leave request form.  This would include creating the controller, views and wiring into the system.

wireframe: https://xd.adobe.com/view/3c938671-1a4e-409d-6c91-fb6df2d58ecc-4aa2/screen/c0a2dc69-2630-4200-980c-1f1bc0bff9f2/Requestor-New-Leave-Request

Make sure the edit screen also follows the new format.

**Comment by hackmastera** [comment]
See start of this work on branch https://github.com/pulibrary/approvals/tree/7-absence-form

**Comment by carolyncole** [comment]
I just rebased the branch to get it in a state that would be ready to work on.

**Comment by axamei** [comment]
Remove "Time" inputs for MVP. Instead, we want to mimic the current HR system, i.e., include a Start Date, End Date, Suggested (calculated) Total Hours.
