### ISSUE TITLE
Document decorator pattern used in this app

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#70]
do we want to utilize the draper gem.  The gem allow you to connect decorated models with the original model through the decorate method.  https://github.com/drapergem/draper

Another possibility is just to create decorators and instantiate them in the controller.

Yes we want to use the decorator pattern.  We have not yet come to a conclusion about which direction to go between draper or rolling our own.

**Comment by hackmastera** [comment]
We went ahead with creating a decorator and instantiating in the controller. We'd like some documentation on the wiki outlining exactly what such a decorator should look like.

E.g.:
A decorator is a plain Ruby class that accepts a model object and potentially additional data. It then explicitly delegates model methods as needed, and override others in local methods. It should be instantiated in a controller and passed to a view template.

Add a small example.

**Comment by carolyncole** [comment]
@hackmastera can you look over the documentation I created: https://github.com/pulibrary/approvals/wiki/Decorators-in-Approvals

**Comment by hackmastera** [comment]
It's great thank you!!
