### ISSUE TITLE
Add feature to purge/deactivate users when they no longer are at Princeton

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#759]
If a user has left Princeton we should deactivate their account in the system.

- [ ] Determine if it is practical to delete accounts. If they must be retained to keep history of requests, they should be deactivated instead.

- [ ] When deactivated remove all delegation relationships with the account.

- [x] When deactivated remove all admin assistant privileges.

**Comment by sandbergja** [comment]
@kevinreiss is this closed by #788 ?

**Comment by sandbergja** [comment]
Closing.  If somebody leaves, they won't be able to log in via CAS anymore.  And the delegation and admin assistant considerations were addressed in #788.
