### ISSUE TITLE
Issue scrolling in Chrome

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#774]
From Martin:
>I asked Patty whether she has the following issue, and apparently she has not.
>
>It seems, when I am asked to approve submitted requests, I don’t get in my browser the right scroll bar, and therefore, have difficulty seeing the whole page. I have to put a cursor on screen, and then use arrow keys to get at the bottom part of the request, but I don’t have the usual scroll bar (it shows up only after approval.)
>
>This is in Chrome.

**Comment by kevinreiss** [comment]
can't replicate this.
