### ISSUE TITLE
Trip ID Format

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#80]
Related to #53. We should confirm that trip ID value that is generated for travel requests takes a form that is reasonable for users to copy/paste and search for with minimal typos. Postgres seems like it has several options. A short numeric value is current pattern provided. It seems like postgres has a lot of flexibility on default ID patterns.

**Comment by carolyncole** [comment]
Will the trip id be different from the primary key.  Maybe it should be minted at some point.  We should have it sequentially after trip ids from the current system.

When does this get minted?  At final approval?  When the request is created?

It may also be possible to tell postgres what number to start the primary key at.

**Comment by hackmastera** [comment]
We've decided to do the postgres configuration of a start value on an incrementing number
