### ISSUE TITLE
Inventory old system in order to seed events / event series

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/approvals#82]
This will be completed when we have a list of trips from managers.

Clean up the list from @axamei comment below.  Add seeding script.
Format should be `Name (Acronym)` eg `American Library Association (ALA)`

**Comment by kevinreiss** [comment]
The best we can do with this compile a list of the major events that departments send multiple folks to every year (i.e. code4lib or ALA Annual/Midwinter). We could also come up with some broad categories for "unique" trips that have a similar purpose (i.e. Site Visit).

**Comment by kevinreiss** [comment]
I will follow-up with department managers and ask for the top events in their groups.

**Comment by axamei** [comment]
Access
ACRL
ACRL NY
American Institute for Conservation
American Library Association (ALA) Annual Conference
American Library Association (ALA) Midwinter Conference
American Musicological Society
ARLIS/NY
Art Libraries Society of North America (ARLIS/NA)
Asbury Agile
Blacklight Summit
Code4Lib
College Art Association (CAA) Annual Conference
Computers in Libraries
DLF Forum
Documents Association of NJ (DANJ)
DrupalCampNJ
DrupalCon
edUI
European Library Automation Group (ELAG)
Geo4LibCamp
IIIF
International Association for Social Science Information Services and Technology (IASSIST)
Ivies+ Access Services Symposium
Ivies+ Discovery Day
LDCX
Mid-Atlantic Regional Archives Conference (MARAC)
Middle East Librarians Association
Middle East Studies Association
Modern Greek Studies Association (MGSA)
Monirotama
Music Library Association
New York Antiquarian Book Fair
NJ ACRL
NJLA
OCLC Resource Sharing Conference
Open Repositories
Preservation and Archiving Special Interest Group (PASIG)
Rare Books and Manuscripts Section (RBMS) Conference
RubyConf
Samvera Connect
Site Visit
Smashing Conference
Society of American Archivists (SAA)
Special Libraries Association (SLA)
Wharton Research Data Services
Workshop
