### ISSUE TITLE
Create Rake Task to export CSV of Trip Data

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#822]
Task will accept the starting and ending dates for the range of trip data desired.

**Comment by maxkadel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Rails-62754f60cf98a10014f28e1e/issues/pulibrary/approvals/822?planning-poker) with Zenhub @leefaisonr @regineheberlein @rladdusaw @sandbergja
