### ISSUE TITLE
Notification Emails Still Include Departmental Assistants that no longer have active relationships with a department

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#823]
Two staff members, Maria DiFalco and Bev Swaszt were previously defined as admin assistants in https://github.com/pulibrary/approvals/blob/main/config/departments.yml but had this association taken away. Notification emails for the departments they previously were attached still copy them on notification messages when a trip is approved. 

Commit where they were removed:

https://github.com/pulibrary/approvals/commit/58b3bb462da7e0a89227db4d33285bd9db9066c6

**Comment by maxkadel** [comment]
It looks like the rake task to remove them from the database was not run - see https://github.com/pulibrary/approvals/blob/main/docs/leaving_princeton.md for documentation.

I've run the rake task on both the staging and production servers, so they should now be removed.
