### ISSUE TITLE
Run tests in parallel on circleci

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#849]
It can take 7 minutes or more for CI to finish, mainly because we have a lot of tests (including a lot of e2e tests).  Making circleci run faster would make working with this app more pleasant.

We did this on orangelight; here's that PR as an example: https://github.com/pulibrary/orangelight/pull/2911/files

**Comment by lizgarciao** [comment]
resolved by https://github.com/pulibrary/approvals/pull/974
