### ISSUE TITLE
Daily Staff Refresh Job needs to consume revised CSV Report 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#854]
A revised daily staff list report is now available in the shared drive under the title "Active Library Staff". The columns headers and filename on the  job processing needs to be adjusted to deal with a new file naming convention and a change in a column name. The "Absence Manager Column" is just "Manager" now. See the files on fileshare configured for the app for a current example file and a the new report format.

**Comment by maxkadel** [comment]
Use LibJobs as model - https://github.com/pulibrary/lib_jobs/commit/9c4f3ab54958f3518f52a7a52291a9fa8cfe3c93
