### ISSUE TITLE
Add report of travel requests including unapproved ones

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/approvals#861]
### User story

As a developer, I would like to run a report of all upcoming travel requests, regardless of whether or not they are approved.

### Concrete example

We got this request today. @christinach and I were able to generate a report of approved travel requests quickly with `bundle exec rake approvals:reports:approved_trips["03/13/2023","03/13/2024"]`.  However, we needed to create a custom one-off report in the rails console to include unapproved requests.  It would be nice to have something ready to go for the next request.

**Comment by anoosh96** [comment]
hey @sandbergja I can raise a PR for this, may I be assigned to this issue?

**Comment by sandbergja** [comment]
closing in favor of #883
