### ISSUE TITLE
Remove "Discretionary" as a travel classification option

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#872]
Currently when a users final supervisor approves a travel request they have the option to flag travel as "discretionary" on the supervisor approval form. We can remove this as a section. LAT has decided that we no longer will classify any any travel as "discretionary". The choice can be removed from the dropdown on the form. Seen in the screenshot below:
![Screen Shot 2023-04-11 at 11.06.18 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/f4bf0d1b-9d2e-4e18-838a-7e08c218c4de)

**Comment by maxkadel** [comment]
There are examples of Requests using "Discretionary" on staging, but none on production.

**Comment by kevinreiss** [comment]
It is possible it has never been used on a real request.
