### ISSUE TITLE
New options for existing field: Category

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#889]
### User story
As an administrator, I would like to have travel requests categorized into four categories:

- Conferences
- Education and Training
- Required Business
- Acquisitions

### Concrete example
- When IT staff request travel funding for All-Hands, it is categorized as "Required Business"

### Acceptance criteria

- When I review a request, the category is displayed
- When I review approved requests, I can filter by category

**Comment by maxkadel** [comment]
Is this a new field that the request submitter assigns? Or is it additional categories for the existing "Travel Category" field that administrators assign?

**Comment by escowles** [comment]
This is an updated set of possible values in the existing travel category list (https://github.com/pulibrary/approvals/blob/main/app/models/request.rb#L66). I believe that "Required Business/Teleworkers on-site" and "Education/Training" map to the existing values, and "Acquisitions/Collections" and "Conferences" are new, if that helps avoid doing a data migration to expand this list.

**Comment by kevinreiss** [comment]
Thanks @escowles. Most of the trips in the system (for IT at least) have been recorded as business travel so if there is a need to filter specifically for teleworkers on site we wouldn't be able to do so on the category value. Is that okay? Or is there a need to filter to just on-site teleworkers in this category?

**Comment by escowles** [comment]
I don't think there is a need to filter to just on-site teleworkers — that was lumped in with other business travel.

**Comment by kevinreiss** [comment]
New travel guidelines reference this https://lib-confluence.princeton.edu/display/LSC/Princeton+University+Library+Travel+Policy+and+Best+Practices

My reading is we should have four categories in this field: 

    

- Conferences
-     Education and Training
-     Required Business
-     Acquisitions

**Comment by kevinreiss** [comment]
@escowles I pulled the categories in my last comment out of the new travel guidelines. Should we utilize those for the revised categories or the ones that are in the first comment on this issue?

**Comment by escowles** [comment]
@kevinreiss Yes, I think it's best to use the wording from the new travel guidelines so they match.
