### ISSUE TITLE
Admin Assistant (AA) submits leave requests for requesters

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#89]
As a departmental administrator I need to act as a proxy user for requesters in my department who need to submit travel and leave requests.

**Comment by sdellis** [comment]
I assume the Dept. Admin can submit leave/travel requests for Departmental Managers as well?

**Comment by carolyncole** [comment]
not MVP

**Comment by carolyncole** [comment]
Against current Policy for user submitting their own information.
