### ISSUE TITLE
New Field: Presenting?

### ISSUE THREAD

**Issue by escowles** [pulibrary/approvals#892]
### User story
As an administrator reviewing travel requests, I would like to be able to see if the user is presenting at the event

### Acceptance criteria
- When I am reviewing a request, I would like to see a "presenting" label when users are presenting
- When I am reviewing approved requests, I would like to be able to filter to when users are presenting or not

**Comment by escowles** [comment]
@jpstroop There is already a "Participation" field with "Presenter" as one of the options. Would it be OK to tag the requests with a "Presenter" label if that level of participation has been selected?

**Comment by kevinreiss** [comment]
The approval screen already does show the participation field which will display "presenter" when that has been selected. 

<img width="531" alt="Screenshot 2023-05-23 at 9 09 22 AM" src="https://github.com/pulibrary/approvals/assets/278825/115b0ed9-1d4c-4fc2-8801-c06d8a358cb2">


I'm not sure adding another tag makes much sense on that screen. We could add this filed as displayed and filterable value on the various reporting screens. How does that sound?
