### ISSUE TITLE
Admin Assistant (AA) needs to approve requests for supervisors

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#90]
As a departmental administrator I need to act as a proxy and approve leave requests on behalf of supervisors in my department.

As a department head I need to be able to assign more than one delegate.

**Comment by hackmastera** [comment]
not mvp

**Comment by carolyncole** [comment]
This could become a security violation, so it maybe that we should allow for this sooner.

**Comment by kevinreiss** [comment]
Can be handled with the delegation.
