### ISSUE TITLE
Show cost and approval date in reports

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/approvals#901]
### User story
As a person in charge of a budget, I need to report on what has been approved to date, and how much it is expected to cost.

### Concrete example
I want to visit, e.g., https://approvals.princeton.edu/reports/ (with whatever filters applied) and have two extra columns appear: the **Total** from the `show` page, and the final approval date.

### Acceptance criteria

- [ ] (See example)
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Implementation notes, if any
The date on which the request was approved could probably always be the final approver for any user, since nothing is really approved until then the final approver has signed off.

1. Add a column to the report view that display to total estimated cost for the trip. 
2. Add a column to the report view that displays the final approval date in the request's history. If we can check to see if that approval was by a terminal approver only displays that final approval date if the result of that check is true. If the final approval date is not by a terminal approver the column can be left blank. 

Also, it would be great if #129 was implemented to support this use case!

**Comment by kevinreiss** [comment]
@jpstroop Requests can have multiple approval dates in their history. We plan to display the final approval date in the history of the request. Let us know if that doesn't work.

**Comment by jpstroop** [comment]
Yes, I think that will work just fine.
