### ISSUE TITLE
Feature tests do not pass locally on main

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/approvals#921]
### Expected behavior
On main, following README instructions, all tests should be passing

### Actual behavior
Feature tests fail with

```
      Webdrivers::VersionError:
        Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
```

### Steps to replicate
1. Follow set-up steps in readme
2. Run `bundle exec rspec spec/features/

### Impact of this bug
It slows development cycles because you can't trust the tests to reflect true failures.

**Comment by christinach** [comment]
With this https://github.com/pulibrary/approvals/tree/i921-fix-local-specs branch I don't see anymore the error that is reported on the issue. 
When I run the feature tests the following tests are failing:
```
rspec ./spec/features/my_requests_spec.rb:12 # My Requests I can filter my requests
rspec ./spec/features/my_requests_spec.rb:55 # My Requests I can sort my requests
rspec ./spec/features/report_spec.rb:17 # My Requests I can filter reports
```

**Comment by sandbergja** [comment]
I am seeing the same results as @christinach locally.

**Comment by christinach** [comment]
Closing as tests are passing now in main.
