### ISSUE TITLE
AASM::InvalidTransition: Event 'change_request' cannot transition from 'changes_requested'

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#987]
### Honeybadger link and code snippet, if applicable

```
201 | if AASM::StateMachineStore.fetch(self.class, true).machine(state_machine_name).config.whiny_transitions
202 | raise AASM::InvalidTransition.new(self, event_name, state_machine_name, failures)
203 | else
204 | false

[/app/controllers/common_request_controller.rb:225 :in `run_action`]
```
[request.aasm.fire(action, agent: current_staff_profile) if request_change_set.valid?](https://github.com/pulibrary/approvals/blob/7fdccf8be6109b5741b3bde4b5933080aaf7e64a/app/controllers/common_request_controller.rb#L225)

### Implementation notes, if any
[Honeybadger error link](https://app.honeybadger.io/projects/67941/faults/103350632)

To identify the cause of this you will need to look up the request ID and see what the last state the request was in and try and identify what the user who was processing/editing the request did to try and advance it to a new state the system failed to understand.

**Comment by kevinreiss** [comment]
The request ID has been successfully "approved" in the system. If you check the StateChange history you can see it was successfully approved so this error didn't prevent it from getting approved.

**Comment by kevinreiss** [comment]
I wrote the request approvers to see if they recall seeing any errors and the context of their action.

**Comment by kevinreiss** [comment]
Heard back, the final approver opened the request and there was no data, the request was sent back to the submitter who filled it out again, sent it back, and then the data was there and the request was successfully approved.

**Comment by christinach** [comment]
[Honeybadger error](https://app.honeybadger.io/projects/67941/faults/103350632)

AASM::InvalidTransition in [travel_requests # decide](https://app.honeybadger.io/projects/67941/faults?q=component:travel_requests%20action:decide#notice-summary)
22 minutes ago - 3/18/2024 at 2:33 PM -04:00

https://approvals.princeton.edu/travel_requests/11261/decide

https://approvals.princeton.edu/travel_requests/11261/review

app/controllers/common_request_controller.rb
```
[PROJECT_ROOT]/app/controllers/common_request_controller.rb:225:in `run_action'
224 request = request_change_set.model
225 request.aasm.fire(action, agent: current_staff_profile) if request_change_set.valid?

```

`AASM::InvalidTransition: Event 'approve' cannot transition from 'approved'.`
